### PR TITLE
TL-19112: Preliminary Prebid Native Support

### PR DESCRIPTION
**Pull request by nllerandi3lift**
## Type of change

- [x] Feature

## Description of change
- Adds support for Prebid Native

This is a work in progress. Many existing tests will need to be updated as well.

### CODE REVIEW

**Comment by nllerandi3lift** [comment]
Successfully tested end to end, running native and banner simultaneously:

image

as well as native alone / banner alone:

image (6)

**Comment by dangoldin** [comment]
@nllerandi3lift Did you want to finish this up?

**Comment by nllerandi3lift** [comment]
I don't want it merged into Prebid just yet. But I have it here because on occasion (though rare) a pub may want to run native via JS. This doesn't need to be PR - could just be a branch.

**Comment by nllerandi3lift** [comment]
Actually going to close this because I have a newer branch with updated tests. 
https://github.com/triplelift-internal/Prebid.js/tree/prebidNative

**Pull request closed without merging**
